[versions]
agp = "8.7.2"
coreKtx = "1.15.0"
exoplayerCore = "2.19.1"
ffmpegKitVideo = "4.5"
glide = "4.14.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
okhttp = "4.9.3"
osmdroidAndroid = "6.1.10"
viewpager2 = "1.1.0"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayerCore" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayerCore" }
ffmpeg-kit-video = { module = "com.arthenica:ffmpeg-kit-video", version.ref = "ffmpegKitVideo" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
osmdroid-wms = { module = "org.osmdroid:osmdroid-wms", version.ref = "osmdroidAndroid" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

